Repository mijien0179/PCTORY, pull requests merged in 2022-05, with the labels that each got.

#2 Form Design
  pctory.design/Properties/AssemblyInfo.cs
  pctory.design/Win32.cs
  pctory.design/pctory.design.csproj
  pctory.design/pctoryButton.Designer.cs
  pctory.design/pctoryButton.cs
  pctory.design/pctoryForm.Designer.cs
  pctory.design/pctoryForm.cs
  pctory.design/tools.cs
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/pctory.csproj
  pctory/pctory.sln
Labels: Design

#7 Log Combine 함수 추가
  pctory/ApiHelper.cs
  pctory/Tracer.cs
Labels: Tools

#9 Update FileIO.cs
  pctory/FileIO.cs
Labels: bug

#5 UI
  pctory.design/pctoryForm.cs
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/Form1.resx
  pctory/Form3.Designer.cs
  pctory/Form3.cs
  pctory/Graph.Designer.cs
Labels: enhancement, Design

#8 Feature file IO
  pctory/ApiHelper.cs
  pctory/FileIO.cs
  pctory/Tracer.cs
  pctory/pctory.csproj
Labels: enhancement

#10 Chart UI 통합, 모달 창 사용
  pctory/Form1.cs
  pctory/Graph.Designer.cs
  pctory/Graph.cs
Labels: enhancement, Design

#13 기능 및 버그 개선
  pctory/Form1.Designer.cs
  pctory/Form1.cs
Labels: bug
