Repository mijien0179/PCTORY, pull requests merged in 2022-06, with the labels that each got.

#20 시작 프로그램 등록/해제 구현
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/Setting.cs
  pctory/pctory.csproj
  pctory/pctory.csproj.user
Labels: enhancement

#19 Topmost Process caption 제대로 뽑지 못하는 문제 수정
  pctory/Tracer.cs
  pctory/WinApi.cs
Labels: bug

#25 트레이서 안정화
  pctory/Form1.cs
  pctory/Setting.cs
  pctory/Tracer.cs
Labels: bug

#24 설정 창 추가
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/Setting.cs
  pctory/fSetting.Designer.cs
  pctory/fSetting.cs
  pctory/fSetting.resx
  pctory/pctory.csproj
Labels: enhancement, Design

#26 날짜 변경 추적 기능 추가
  pctory/DayTrace.cs
  pctory/Form1.cs
  pctory/pctory.csproj
Labels: Tools

#27 Windows 시작시 폼 숨기기
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/Form1.resx
  pctory/Program.cs
  pctory/Setting.cs
  pctory/pctory.csproj.user
Labels: enhancement

#28 Conference Chart
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/Graph.Designer.cs
  pctory/Graph.cs
Labels: enhancement, Design, Tools

#17 Update readme.md
  readme.md
Labels: documentation

#31 파일 연결프로그램 레지스트리 설정 및 로그, 실행파일 아이콘 설정
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/Form1.resx
  pctory/Icon1.ico
  pctory/Properties/Resources.Designer.cs
  pctory/Properties/Resources.resx
  pctory/Setting.cs
  pctory/pctory.csproj
Labels: enhancement

#29 Selection chart data
  pctory/Form1.cs
  pctory/Graph.Designer.cs
  pctory/Graph.cs
Labels: enhancement

#30 로그 뷰어 추가
  pctory/Form1.Designer.cs
  pctory/Form1.cs
  pctory/Program.cs
  pctory/fViewer.Designer.cs
  pctory/fViewer.cs
  pctory/fViewer.resx
  pctory/pctory.csproj
  pctory/viewInitializer.cs
Labels: enhancement, Design

#35 Feature chart
  pctory/Form1.cs
  pctory/Graph.Designer.cs
  pctory/Graph.cs
Labels: bug, enhancement

#37 파일 뷰어 개선
  pctory.design/pctoryForm.cs
  pctory/Form1.Designer.cs
  pctory/fViewer.Designer.cs
  pctory/fViewer.cs
  pctory/fViewer.resx
  pctory/viewInitializer.cs
Labels: enhancement, Design

#39 로그 자동저장 기능 구현
  pctory/DayTrace.cs
  pctory/Form1.cs
Labels: enhancement
